using FluentAssertions;
using Xunit;

namespace VocaDb.ResXFileCodeGenerator.Tests;

public class HelperGeneratorTests
{
	[Fact]
	public void CanGenerateCombo()
	{
		var (generatedFileName, sourceCode, errorsAndWarnings) = new StringBuilderGenerator()
			.Generate(new CultureInfoCombo(new []{new AdditionalTextStub("test.da.rex"), new AdditionalTextStub("test.da-dk.rex")}), default);
		var expected = @"// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace VocaDb.ResXFileCodeGenerator;
internal static partial class Helpers
{
    public static string GetString_1030_6(string fallback, string da_DK, string da) => System.Globalization.CultureInfo.CurrentUICulture.LCID switch {
        1030 => da_DK,
        6 => da,
        _ => fallback
    };
}
";
		errorsAndWarnings.Should().BeNullOrEmpty();
		generatedFileName.Should().Be("VocaDb.ResXFileCodeGenerator.1030_6.g.cs");
		sourceCode.Should().Be(expected);
	}
	[Fact]
	public void CanGenerateEmptyCombo()
	{
		var (generatedFileName, sourceCode, errorsAndWarnings) = new StringBuilderGenerator().Generate(new CultureInfoCombo(), default);
		var expected = @"// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace VocaDb.ResXFileCodeGenerator;
internal static partial class Helpers
{
    public static string GetString_(string fallback) => System.Globalization.CultureInfo.CurrentUICulture.LCID switch {
        _ => fallback
    };
}
";
		errorsAndWarnings.Should().BeNullOrEmpty();
		generatedFileName.Should().Be("VocaDb.ResXFileCodeGenerator..g.cs");
		sourceCode.Should().Be(expected);
	}
}
