using System.Globalization;
using System.Resources;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Xml;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;

namespace VocaDb.ResXFileCodeGenerator;

public sealed class StringBuilderGenerator : IGenerator
{
	private static readonly Regex s_validMemberNamePattern =
		new(@"^[\p{L}\p{Nl}_][\p{Cf}\p{L}\p{Mc}\p{Mn}\p{Nd}\p{Nl}\p{Pc}]*$",
			RegexOptions.Compiled | RegexOptions.CultureInvariant);

	private static readonly Regex s_invalidMemberNameSymbols = new(@"[^\p{Cf}\p{L}\p{Mc}\p{Mn}\p{Nd}\p{Nl}\p{Pc}]",
		RegexOptions.Compiled | RegexOptions.CultureInvariant);

	private static readonly DiagnosticDescriptor s_duplicateWarning = new("VocaDbResXFileCodeGenerator001",
		"Duplicate member",
		"Ignored added member '{0}'",
		"ResXFileCodeGenerator",
		DiagnosticSeverity.Warning,
		true);

	private static readonly DiagnosticDescriptor s_memberSameAsClassWarning = new("VocaDbResXFileCodeGenerator002",
		"Member same name as class",
		"Ignored member '{0}' has same name as class",
		"ResXFileCodeGenerator",
		DiagnosticSeverity.Warning,
		true);

	private static readonly DiagnosticDescriptor s_memberWithStaticError = new("VocaDbResXFileCodeGenerator003",
		"Incompatible settings",
		"Cannot have static members/class with an class instance",
		"ResXFileCodeGenerator",
		DiagnosticSeverity.Error,
		true);

	public (string generatedFileName, string SourceCode, IEnumerable<Diagnostic> ErrorsAndWarnings) Generate(
		TextReader resxStream, FileOptions options, CancellationToken cancellationToken = default)
	{
		var errorsAndWarnings = new List<Diagnostic>();

		// HACK: netstandard2.0 doesn't support improved interpolated strings?
		var builder = GetBuilder();

		builder.AppendLine(Constants.AutoGeneratedHeader);
		builder.AppendLine("#nullable enable");

		builder.Append("namespace ");
		builder.AppendLine(options.CustomToolNamespace ?? options.LocalNamespace);
		builder.AppendLine("{");

		builder.Append("    using ");
		builder.Append(Constants.SystemGlobalization);
		builder.AppendLine(";");

		builder.Append("    using ");
		builder.Append(Constants.SystemResources);
		builder.AppendLine(";");

		builder.AppendLine();

		builder.Append("    ");
		builder.Append(options.PublicClass ? "public" : "internal");
		builder.Append(options.PartialClass ? " partial" : "");
		builder.Append(options.StaticClass ? " static class " : " class ");
		builder.AppendLine(options.ClassName);
		builder.AppendLine("    {");

		var indent = "        ";
		string containerClassName = options.ClassName;

		if (options.InnerClassVisibility != InnerClassVisibility.NotGenerated)
		{
			containerClassName = string.IsNullOrEmpty(options.InnerClassName) ? "Resources" : options.InnerClassName;
			if (!string.IsNullOrEmpty(options.InnerClassInstanceName))
			{
				if (options.StaticClass || options.StaticMembers)
				{
					errorsAndWarnings.Add(Diagnostic.Create(s_memberWithStaticError,
						Location.Create(options.FilePath, new(), new())));
				}

				builder.Append(indent);
				builder.Append("public ");
				builder.Append(containerClassName);
				builder.Append(" ");
				builder.Append(options.InnerClassInstanceName);
				builder.AppendLine(" { get; } = new();");
				builder.AppendLine();
			}

			builder.Append(indent);
			builder.Append(options.InnerClassVisibility == InnerClassVisibility.SameAsOuter
				? options.PublicClass ? "public" : "internal"
				: options.InnerClassVisibility.ToString().ToLowerInvariant());
			builder.Append(options.PartialClass ? " partial" : "");
			builder.Append(options.StaticClass ? " static class " : " class ");

			builder.AppendLine(containerClassName);
			builder.Append(indent);
			builder.AppendLine("{");

			indent += "    ";

		}

		builder.Append(indent);
		builder.Append("private static ");
		builder.Append(nameof(ResourceManager));
		builder.Append("? ");
		builder.Append(Constants.s_resourceManagerVariable);
		builder.AppendLine(";");

		builder.Append(indent);
		builder.Append("public static ");
		builder.Append(nameof(ResourceManager));
		builder.Append(" ");
		builder.Append(Constants.ResourceManagerVariable);
		builder.Append(" => ");
		builder.Append(Constants.s_resourceManagerVariable);
		builder.Append(" ??= new ");
		builder.Append(nameof(ResourceManager));
		builder.Append("(\"");
		builder.Append(options.EmbeddedFilename);
		builder.Append("\", typeof(");
		builder.Append(containerClassName);
		builder.AppendLine(").Assembly);");

		builder.Append(indent);
		builder.Append("public ");
		builder.Append(options.StaticMembers ? "static " : "");
		builder.Append(nameof(CultureInfo));
		builder.Append("? ");
		builder.Append(Constants.CultureInfoVariable);
		builder.AppendLine(" { get; set; }");

		if (XDocument.Load(resxStream, LoadOptions.SetLineInfo).Root is { } element)
		{
			var members = element
				.Descendants()
				.Where(static data => data.Name == "data")
				.Select(static data => (data.Attribute("name")!.Value, data.Descendants("value").First().Value,
					(IXmlLineInfo)data.Attribute("name")!));

			HashSet<string> alreadyAddedMembers = new() { Constants.CultureInfoVariable };
			foreach (var ((key, value, line), index) in members.Select((kv, index) => (kv, index)))
			{
				cancellationToken.ThrowIfCancellationRequested();
				CreateMember(indent, builder, options, key, value, line, alreadyAddedMembers, errorsAndWarnings, containerClassName);
			}
		}

		if (options.InnerClassVisibility != InnerClassVisibility.NotGenerated)
		{
			builder.AppendLine("        }");
		}

		builder.AppendLine("    }");

		builder.Append("}");

		return ($"{options.LocalNamespace}.{options.ClassName}.g.cs", builder.ToString(), errorsAndWarnings);
	}

	static void CreateMember(string indent, StringBuilder builder, FileOptions options, string name, string value,
		IXmlLineInfo line, HashSet<string> alreadyAddedMembers, List<Diagnostic> errorsAndWarnings,
		string containerclassname)
	{
		string memberName;
		bool resourceAccessByName;

		if (s_validMemberNamePattern.IsMatch(name))
		{
			memberName = name;
			resourceAccessByName = true;
		}
		else
		{
			memberName = s_invalidMemberNameSymbols.Replace(name, "_");
			resourceAccessByName = false;
		}

		static Location GetMemberLocation(FileOptions fileOptions, IXmlLineInfo line, string memberName) =>
			Location.Create(fileOptions.FilePath, new(),
				new(new(line.LineNumber - 1, line.LinePosition - 1),
					new(line.LineNumber - 1, line.LinePosition - 1 + memberName.Length)));

		if (!alreadyAddedMembers.Add(memberName))
		{
			errorsAndWarnings.Add(Diagnostic.Create(s_duplicateWarning, GetMemberLocation(options, line, memberName),
				memberName));
			return;
		}

		if (memberName == containerclassname)
		{
			errorsAndWarnings.Add(Diagnostic.Create(s_memberSameAsClassWarning,
				GetMemberLocation(options, line, memberName), memberName));
			return;
		}

		builder.AppendLine();

		builder.Append(indent);
		builder.AppendLine("/// <summary>");

		builder.Append(indent);
		builder.Append("/// Looks up a localized string similar to ");
		builder.Append(HttpUtility.HtmlEncode(value.Trim().Replace("\r\n", "\n").Replace("\r", "\n")
			.Replace("\n", Environment.NewLine + "        /// ")));
		builder.AppendLine(".");

		builder.Append(indent);
		builder.AppendLine("/// </summary>");

		builder.Append(indent);
		builder.Append("public ");
		builder.Append(options.StaticMembers ? "static " : "");
		builder.Append("string");
		builder.Append(options.NullForgivingOperators ? null : "?");
		builder.Append(" ");
		builder.Append(memberName);

		if (resourceAccessByName)
		{
			builder.Append(" => ResourceManager.GetString(nameof(");
			builder.Append(name);
			builder.Append("), ");
		}
		else
		{
			builder.Append(@" => ResourceManager.GetString(""");
			builder.Append(name.Replace(@"""", @"\"""));
			builder.Append(@""", ");
		}

		builder.Append(Constants.CultureInfoVariable);
		builder.Append(")");
		builder.Append(options.NullForgivingOperators ? "!" : null);
		builder.AppendLine(";");
	}


	private static StringBuilder GetBuilder()
	{
		return new();
	}
}
